# Generated by Django 5.1.7 on 2025-12-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_options_alter_user_username'),
    ]

    operations = [
    ]
